"""create_table_CentralCoast

Revision ID: 6f10cc7ca888
Revises: 4544fae73d7b
Create Date: 2024-05-02 17:13:54.604568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '6f10cc7ca888'
down_revision: Union[str, None] = '4544fae73d7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('kalamunda', 'lodgement_date',
               existing_type=mysql.INTEGER(),
               type_=sa.DateTime(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('kalamunda', 'lodgement_date',
               existing_type=sa.DateTime(),
               type_=mysql.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
