"""create_table_CentralCoast

Revision ID: 9b91978991ee
Revises: 6f10cc7ca888
Create Date: 2024-05-02 17:32:50.756649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '9b91978991ee'
down_revision: Union[str, None] = '6f10cc7ca888'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('kalamunda', 'lodgement_date',
               existing_type=mysql.DATETIME(),
               type_=sa.Integer(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('kalamunda', 'lodgement_date',
               existing_type=sa.Integer(),
               type_=mysql.DATETIME(),
               existing_nullable=True)
    # ### end Alembic commands ###
